#pragma once

#include "game/interfaces/engine.hpp"
#include "game/interfaces/client.hpp"
#include "game/interfaces/cliententitylist.hpp"
#include "game/interfaces/client_mode.hpp"
#include "game/interfaces/surface.hpp"
#include "game/interfaces/lua_shared.hpp"
#include "game/interfaces/i_panel.hpp"
#include "game/interfaces/debugoverlay.hpp"
#include "game/interfaces/imaterialsystem.hpp"
#include "game/interfaces/convar.hpp"
#include "game/interfaces/random_stream.hpp"
#include "game/interfaces/iprediction.hpp"
#include "game/interfaces/ienginetrace.hpp"
#include "game/interfaces/globalvars.hpp"
#include "game/interfaces/gamemovement.hpp"
#include "game/interfaces/movehelper.hpp"
#include "game/interfaces/cinput.hpp"

#include "game/entities/c_base_weapon.hpp"
#include "game/misc/md5_check_sum.h"